-- Create Vouchers Table
CREATE TABLE public.vouchers (
    id bigint generated by default as identity primary key,
    code text not null unique,
    product_id int not null, 
    product_name text, -- Added for easier display
    user_id uuid references public.users(id), -- Changed to UUID to match users table
    
    -- Status and Source
    status text check (status in ('active', 'redeemed', 'expired', 'void')) default 'active',
    source_type text check (source_type in ('digital_purchase', 'paper_converted')) not null,
    original_paper_code text, -- For paper_converted source
    
    -- Timestamps
    valid_from timestamp with time zone,
    valid_until timestamp with time zone,
    redeemed_at timestamp with time zone,
    redeemed_by text, -- Store store/staff info
    created_at timestamp with time zone default now()
);

-- Create Voucher Logs Table
CREATE TABLE public.voucher_logs (
    id bigint generated by default as identity primary key,
    voucher_id bigint references public.vouchers(id) on delete cascade,
    action text not null, -- created, converted, redeemed, voided, extended, reset
    operator_id uuid references public.admins(id), -- Referencing admins table if possible, or just text
    operator_name text, -- Snapshot of operator name
    memo text,
    created_at timestamp with time zone default now()
);

-- RLS Policies (Simple Admin Access)
alter table public.vouchers enable row level security;
alter table public.voucher_logs enable row level security;

create policy "Admins can view all vouchers" on public.vouchers for select using (true);
create policy "Admins can insert vouchers" on public.vouchers for insert with check (true);
create policy "Admins can update vouchers" on public.vouchers for update using (true);

create policy "Admins can view logs" on public.voucher_logs for select using (true);
create policy "Admins can insert logs" on public.voucher_logs for insert with check (true);

-- Insert Dummy Data for Testing
INSERT INTO public.vouchers (code, product_id, product_name, user_id, status, source_type, valid_from, valid_until)
SELECT 
  'EV-' || substr(md5(random()::text), 1, 8), 
  101, 
  '平日18洞果嶺券', 
  id, 
  'active', 
  'digital_purchase', 
  now(), 
  now() + interval '6 months'
FROM public.users 
LIMIT 5;

INSERT INTO public.vouchers (code, product_id, product_name, user_id, status, source_type, original_paper_code, valid_from, valid_until)
SELECT 
  'PAP-' || substr(md5(random()::text), 1, 8), 
  102, 
  '假日擊球優惠券', 
  id, 
  'active', 
  'paper_converted', 
  'P8825252',
  now(), 
  now() + interval '1 year'
FROM public.users 
LIMIT 3;
