-- ============================================================
-- voucher_packages：記錄客戶購買的套本（A/B 套本）
--
-- 用途：
--   - 一位客戶同時最多只能有一筆 active 套本
--   - 發套本前檢查是否已有 active 套本（擋重複購買 / 判斷續約）
--   - 全部退券時，將 active 套本標記為 cancelled → 可再購買
--
-- 執行：到 Supabase SQL Editor 貼上執行一次
-- ============================================================

CREATE TABLE IF NOT EXISTS public.voucher_packages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id),
  package_index int not null,
  package_name text not null,
  price int not null default 0,
  green_fee_count int not null default 0,
  product_count int not null default 0,
  valid_from date,
  valid_until date,
  is_renewal boolean not null default false,
  status text not null default 'active',   -- active | renewed | cancelled
  operator_name text,
  created_at timestamptz not null default now(),
  cancelled_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_voucher_packages_user
  ON public.voucher_packages(user_id);

-- 每位客戶最多一筆 active（部分唯一索引，DB 層防重複購買）
CREATE UNIQUE INDEX IF NOT EXISTS uq_voucher_packages_active_user
  ON public.voucher_packages(user_id)
  WHERE status = 'active';

-- service_role 存取（後端用 service key）
ALTER TABLE public.voucher_packages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role full access" ON public.voucher_packages;
CREATE POLICY "service_role full access" ON public.voucher_packages
  FOR ALL TO service_role USING (true) WITH CHECK (true);
