-- ============================================================
-- voucher_transfers：記錄會員之間的票券轉贈，供後續追蹤與找尋來源
--
-- 用途：
--   - 會員在 LINE 會員專區把自己未使用的電子券轉給另一位會員
--   - 每次轉贈留一筆紀錄（來源/收禮雙方、券種、張數、實際轉出的券 id/code）
--   - 可回溯某張券是從誰轉來的
--
-- 執行：到 Supabase SQL Editor 貼上執行一次
-- ============================================================

CREATE TABLE IF NOT EXISTS public.voucher_transfers (
  id bigint generated by default as identity primary key,
  from_user_id uuid not null references public.users(id),
  to_user_id uuid not null references public.users(id),
  from_name text,
  from_phone text,
  to_name text,
  to_phone text,
  voucher_type text not null,          -- green_fee | product
  product_name text,                   -- 果嶺券 | 商品券
  quantity int not null,
  voucher_ids bigint[],                -- 實際轉出的券 id（追溯來源）
  voucher_codes text[],                -- 實際轉出的券號（方便人工比對）
  initiated_by text not null default 'member',  -- member（會員自轉）
  created_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS idx_voucher_transfers_from ON public.voucher_transfers(from_user_id);
CREATE INDEX IF NOT EXISTS idx_voucher_transfers_to ON public.voucher_transfers(to_user_id);
CREATE INDEX IF NOT EXISTS idx_voucher_transfers_created ON public.voucher_transfers(created_at);

ALTER TABLE public.voucher_transfers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role full access" ON public.voucher_transfers;
CREATE POLICY "service_role full access" ON public.voucher_transfers
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================================
-- 原子性轉贈：鎖定要轉的券 → 改綁 → 寫轉贈紀錄 → 寫 log，全在同一交易內
-- 避免併發超轉、以及「券已轉走但無紀錄」的孤兒轉贈
-- ============================================================
CREATE OR REPLACE FUNCTION public.transfer_member_vouchers(
  p_from_user uuid,
  p_to_user uuid,
  p_voucher_type text,
  p_product_name text,
  p_qty int,
  p_from_name text,
  p_from_phone text,
  p_to_name text,
  p_to_phone text
) RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  v_ids bigint[];
  v_codes text[];
  v_count int;
BEGIN
  -- 鎖定最舊的 p_qty 張「未使用、非紙券」電子券
  SELECT array_agg(sub.id ORDER BY sub.created_at),
         array_agg(sub.code ORDER BY sub.created_at)
    INTO v_ids, v_codes
  FROM (
    SELECT id, code, created_at
    FROM public.vouchers
    WHERE user_id = p_from_user
      AND product_name = p_product_name
      AND status = 'active'
      AND source_type = 'digital_purchase'
    ORDER BY created_at ASC
    LIMIT p_qty
    FOR UPDATE
  ) sub;

  v_count := COALESCE(array_length(v_ids, 1), 0);
  IF v_count < p_qty THEN
    RAISE EXCEPTION 'INSUFFICIENT:%', v_count;
  END IF;

  UPDATE public.vouchers SET user_id = p_to_user WHERE id = ANY(v_ids);

  INSERT INTO public.voucher_transfers(
    from_user_id, to_user_id, from_name, from_phone, to_name, to_phone,
    voucher_type, product_name, quantity, voucher_ids, voucher_codes, initiated_by
  ) VALUES (
    p_from_user, p_to_user, p_from_name, p_from_phone, p_to_name, p_to_phone,
    p_voucher_type, p_product_name, p_qty, v_ids, v_codes, 'member'
  );

  INSERT INTO public.voucher_logs(voucher_id, action, operator_name, memo)
  SELECT unnest(v_ids), 'transferred',
         COALESCE(p_from_name, p_from_phone, '會員'),
         '會員轉贈：' || COALESCE(p_from_name, p_from_phone, '') || ' → ' || COALESCE(p_to_name, p_to_phone, '');

  RETURN jsonb_build_object('transferred', v_count);
END;
$$;
